[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = default.csv

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.0
    knolleary/PubSubClient @ ^2.8

upload_speed = 921600
monitor_filters = direct

; Allow overriding SDK functions
build_flags = 
    -Wl,--allow-multiple-definition